markdown: rdiscount
permalink: /:title/
url: http://wangclover.github.io/
name: wangclover
author: wang cheng
qq: 568135179
email: 568135179@qq.com
duoshuo: Rkccr
#beian: 浙ICP备12026616号
cnzz: 568135179@qq.com
weibo: 1729033973
github: wangclover
pygments: true
safe: true
paginate: 20
about: "这里是 wangclover 的个人博客，创建于2014年10月。无论风暴把我带到什么岸边，我都将以主人的身份上岸。"
