markdown: rdiscount
permalink: /:title/
url: http://wangclover.tk
name: wangclover.tk
author: wang cheng
qq: 568135179
email: 568135179@qq.com
duoshuo: yonsm
beian: 浙ICP备12026616号
cnzz: 119959
weibo: 1729033973
github: wangclover
pygments: true
safe: true
paginate: 20
about: "这里是 wangclover 的个人博客，创建于 2014 年。